global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api_server'
    static_configs:
      - targets: ['api_server:8000']

  - job_name: 'admin_server'
    static_configs:
      - targets: ['admin_server:8001']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
