version: '3.7'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  api_server:
    build: ./api_server
    depends_on:
      - kafka
      - mongodb
    ports:
      - "8000:8000"

  admin_server:
    build: ./admin_server
    depends_on:
      - mongodb
    ports:
      - "8001:8000"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus_config:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:
