apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server-deployment
  labels:
    app: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: your-docker-account/admin-server:latest
        ports:
        - containerPort: 8001
